version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 main.py'
    ports:
      - "8000:8000"

  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    hostname: localhost
    ports:
      - "5432:5432"

  test_db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=hse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    hostname: localhost
    ports:
      - "5433:5432"